version: "3"

services:
  web:
    build: ./web
    restart: always
    ports:
      - "8012:80"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M

  db:
    hostname: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./db:/docker-entrypoint-initdb.d/